### ISSUE TITLE
Can't mount LUKS external drives 

### ISSUE THREAD

**Issue by msmafra** [pop-os/cosmic-files#144]
I'm no able to mount any of my USB external drives that are encrypted via LUKS. I have to use Nautilus or unencrypt it via terminal.

Fedora Workstation 40
NVIDIA drivers 550.78 (Hybrid mode with Intel i7 10750h)
COSMIC from ryanabx/cosmic-epoch COPR updated 07/05/2024

**Comment by jorge-menjivar** [comment]
Having a pop up ask for the password like gnome files (nautilus) when you click on an encrypted drive would be nice

![image](https://github.com/pop-os/cosmic-files/assets/16660534/8ee81e35-8e14-47c1-9235-471faf9192b6)

**Comment by py-crash** [comment]
In the alpha there is also the  workaround of  to unlock and mount the drive using gnome-disks

**Comment by desmond-git** [comment]
Seems that any partition which you have to enter a password to mount can not be mounted in Cosmic files.
I can not mount any NTFS partitions and I thought that it was a bug but not I know it's a missing feature.
I hope this will be implemented soon because it is annoying having to mount disks from gnome-disks every time.
