### ISSUE TITLE
Middle-click to open in background

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-files#261]
Similar to Nautilus and Dolphin, it would be nice to be able to middle-click folders (in the main view, sidebar, and breadcrumbs) to be able to open them in a new tab, instead of having to right-click and use the context menu.

**Comment by jacobgkau** [comment]
This seems to be working now. This does focus the new tab immediately, which makes it take longer to e.g. open a row of adjacent folders in separate tabs. Nautilus and Dolphin both open tabs in the background (similarly to web browsers opening links in the background when middle-clicking). @pop-os/ux Can you confirm if focusing the new tab is the intended behavior?

**Comment by maria-komarova** [comment]
After some internal discussion and more thinking, let's stick with what is familiar to people from Nautilus.

**Comment by WatchMkr** [comment]
Currently opens and focuses tab. Open in background instead.

**Comment by LeoBeliik** [comment]
> Open in background instead.

I would actually love a toggle in the config for that, I understand everyone's workflow may differ, for me if I'm opening a new tab is because I want to do something in that folder so having it on focus would be desirable.
Furthermore, Dolphin (I don't know if it's the case in Nautilus), let's you auto focus to the new tab by using Shift + Middle click, right now Cosmic Files doesn't have this option (it just select folders like if you were using shift right click).
The desirable feature here would be to have a toggle in the app config to change if you want new tabs to auto focus or not, and shift + middle click would do the opposite.

Thanks!
