### ISSUE TITLE
File listing not updated after renaming a file. 

### ISSUE THREAD

**Issue by zsilet** [pop-os/cosmic-files#418]
1. Pick any file in the directory (log2.txt) right click and rename it (log3.txt)
2. Note that after renaming, the file list still shows the old name (log2.txt)  << This is the issue
3. Repeat step 1. Note that when you type log3.txt as the new name, the dialog says "A file with that name already exists" << Nice touch btw!
4. Cancel.
5. There is no option to refresh? F5 doesn't work, and there is no menu option that I can find. Arrgh.
6. Navigate out of the folder and back in. 
7. Notice that log3.txt is now showing up (from step 1). 

![image](https://github.com/user-attachments/assets/0f6333a1-7561-4509-9b8e-1d57b7da6237)

**Comment by l-const** [comment]
Hey , I couldn't reproduce it myself, from my understanding we do not need any refresh because we use file watchers using the https://github.com/notify-rs/notify package and get potential updates every 250ms from the little code I understand here: https://github.com/pop-os/cosmic-files/blob/master/src/app.rs#L2687 and we essentially rescan the contents if the event we received was type: modify and was related in general.  Maybe something wrong is happening with the watchers / notify.

**Comment by l-const** [comment]
Might be caused by this: https://github.com/pop-os/cosmic-files/issues/429

**Comment by zsilet** [comment]
I have just verified that I can no longer reproduce this issue either, and indeed I was having watcher issues at the same exact time I was seeing this issue. Since @l-const you logged a new issue for the watchers, I am closing.

**Comment by zsilet** [comment]
I have just verified that I can no longer reproduce this issue either, and indeed I was having watcher issues at the same exact time I was seeing this issue. Since @l-const you logged a new issue for the watchers, I am closing this issue.
