### ISSUE TITLE
Design draft

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-files#6]
Although it's 2 years old, we have good ideas in our first files design iteration.

https://www.figma.com/proto/ZaRbmKKhMtfQWZFNrZyj2y/App-experiments?node-id=2-229&starting-point-node-id=2%3A229

**NavBar**
* Recent at top (not in the design)
* All directories (except "Home") and files are "Favorites". This allows users to remove "Music" or "Trash" if they aren't frequently used
* Favorite files are separated from favorite directories
* Favorite directories and files can be dragged and dropped to arrange them
* We'll need a storage section for mounted drives
* Something like "Other locations" for browsing the entire file system and networks (which can be added to favorites to include them in "Other locations"

**Header**
We've moved to a menubar in other cosmic apps. We likely want to do that for cosmic-files. Draft [here](https://github.com/pop-os/cosmic-files/issues/5)

**File previews (and properties)**
* In the ContextDrawer
* Perhaps a TabBar to switch between properties and setting file permissions

**Breadcrumbs**
* We need "Back" and "Forward" buttons which should probably go to the left of breadcrumbs. For fit, in single column view, do we need to remove breadcrubs and only show the directory name?
* "Back" means last directory not necessarily up a directory
* Breadcrumbs bar can be edited to enter a path
* What happens when the breadcrumb list gets long? Only show the last three?

**Find/Search**
* Use the same FindBar we designed for Edit and Terminal?
* Type to initiate find along with the menu item and shortcut?
* Advanced find (time period (day, days, weeks, year, all) and type of file)

**Comment by jackpot51** [comment]
I have concerns with removing Trash. There's no easy way to get there if someone removes it, and it is where files that are deleted go by default.

**Comment by loligans** [comment]
> File previews (and properties)

It would be super nice if there was the ability to quickly preview a file by pressing space. This is a usability enhancement that I believe to be extremely convenient.

> What happens when the breadcrumb list gets long?

Often when this happens it can make editing the path manually difficult because there isn't enough free space to activate the text input with the mouse. I feel like this situation should be considered when designing what happens when the list gets long.

> I have concerns with removing Trash. There's no easy way to get there if someone removes it, and it is where files that are deleted go by default.

It feels perfectly acceptable to have a sane default that works for most users, which includes the `Trash`. Having the option to hide it through settings would be a good middle ground I think.

**Comment by leviport** [comment]
Regarding typing to start a search... This is something that has always annoyed me with Nautilus. If I start typing in ~, it starts a really big search, which slows it down for a long period of time, then shows me tons of results in really deep subdirectories. 

In many other file managers, like Thunar, Nemo, and Windows Explorer, it acts less like a full-on search and highlights the matching item in the current directory. For me, this makes keyboard-only navigation MUCH faster. I type the first few letters of a directory I want to go to, it selects it instantly, I hit Enter, then repeat until I'm in the directory I want to be in.

Full-on file search can still be done with Ctrl + F, or by clicking the search button, but I find myself needing that functionality much more rarely than I use the keyboard navigation method described above.

**Comment by git-f0x** [comment]
Adding to this with a somewhat different design (from the current master), but that can provide good support for splits (including a way to highlight the focused split), per split search and a bigger target for editing path.
Very rough, shouldn't be taken as is. Will just copy my comment from Mattermost:

This would work with splits and the search bar uses the space of the path bar if the search button is clicked (and likely also when typing is started with nothing selected). The search might work by searching all files and directories (and contents of those directories, but maybe only when the button is clicked, since I've seen some comments that find full search with just typing annoying) in the current directory (e.g. in splits, there can be multiple search bars searching from multiple directories). Clicking on any empty area of the path bar (maybe also including the current page, 'cosmic' in the image) would trigger path edit.
Edit: The bar should maybe be a bit thicker (or should have a pill shape unless the square theme is set).
The bars could also be used to indicate focus in splits, since there is a bar per split (e.g. if a split is unfocused, the letters and icons in the bar turn gray, and maybe the bar background turns darker or invisible).
![screenshot-2024-03-22-21-52-37-im8w7p963b8rtgshgbgcd1yjre](https://github.com/pop-os/cosmic-files/assets/150025636/9af2cd1a-fb92-41de-bed1-f3a4df673cf1)


If the current page in the path would be clickable (clicking it doesn't do anything at the moment), then when the path gets too long, path edit can be accessed by clicking on it (provided that the path overflows to the left, i.e. the highest level directories get removed from view first).
