### ISSUE TITLE
[Feature Request] 50% icon size option for list view

### ISSUE THREAD

**Issue by soccerboys2008** [pop-os/cosmic-files#98]
here is an example from nautilus:
![Screenshot from 2024-03-24 23-45-36](https://github.com/pop-os/cosmic-files/assets/29149297/bc12fc76-a603-4302-b083-3b45d21aceb4)

here is what cosmic is currently capable of (ignore missing icons, no idea what's happening there):
![Screenshot from 2024-03-24 23-51-24](https://github.com/pop-os/cosmic-files/assets/29149297/0abac643-5a6e-4d96-b29a-043fb0a99aa1)

**Comment by joshuamegnauth54** [comment]
The missing icons issue is tracked in #48 which I'm trying to fix now.

As for this issue, I'll leave it open for another contributor as the fix seems pretty small. I don't want to hog them.

Take a look at `src/app.rs` near line 539 if you know a bit of Rust.

**Comment by soccerboys2008** [comment]
unfortunately i don't know rust, my experience currently lies in python

**Comment by git-f0x** [comment]
The fix doesn't seem to be that small @joshuamegnauth54.
When the list size is <100%, all text in the mouse_area stops displaying. Usually the font size is the same, regardless of size (in both grid and list view), but it seems the padding at list sizes below 100% prevents the text from showing up (the icons also seems a bit too small at 50%). So different padding might be necessary at smaller sizes.
Another possible fix is to make the padding for the sorting headings (Name, Modified, Size) fixed, since it doesn't need to resize (and looks weird) when changing list size (and they also disappear when <100%).
![screenshot-2024-04-08-23-03-01](https://github.com/pop-os/cosmic-files/assets/150025636/39bea825-5df6-41a4-a5b0-5648bd2da356)

Unfortunately, I'm not familiar enough with Rust and the codebase to attempt to do this.
